# Generated by Django 5.2.5 on 2025-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Funcionario',
            },
        ),
    ]
