# Generated by Django 5.2.5 on 2025-08-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='departament',
            field=models.ForeignKey(db_column='departament_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.departamento'),
        ),
    ]
